DATA:
    ROOT: 'data/rader27'
    TRAIN_FILE: 'data/Split/rader6/4-shot_train.txt'
    VAL_FILE: 'data/Split/rader6/val.txt'
    DATASET: rader6
    NUM_FRAMES: 32
    NUM_CLASSES: 6
    LABEL_LIST: 'labels/rader_6_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 1
    ACCUMULATION_STEPS: 2
    EPOCHS: 25
    LR: 2.e-6